services:

  backend:
    build: ./backend
    container_name: test-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: test-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

